# Summary

<p>
This project was started with a preparation for coding interviews in mind.<br>
It escalated further into an investigation of core Python concepts.</p>
Several topics are investigated, for example:
</p>

<ul>
  <li>performance measurement</li>
  <li>memory usage</li>
  <li>arrays</li>
  <li>dicts</li>
  <li>tuple</li>
  <li>comprehensions</li>
  <li>lambdas</li>
  <li>Numpy</li>
  <li>data frames</li>
  <li>loops</li>
  <li>recursion</li>
  <li>functional programming and recursion</li>
</ul> 

<p>Also problems like the "Missing numbers problem" are considered.<br>
However the project is not complete and will be revisted.</p>

# Import packages

In [1165]:
import pandas as pd
import numpy as np
import random
import os as os
import time
from time import time
from time import sleep
import itertools
import re
import pprint
import sys
import re
import json
import math
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import psutil
import operator
import itertools
from timeit import timeit



In [1166]:
cwd=os.getcwd()
# print(cwd)

directories = os.listdir()
print(directories)

['.ipynb_checkpoints', 'csv', 'python_corepython_concepts.ipynb']


In [1167]:
#Psutil working?
print(psutil.Process().memory_info().rss / (2 * 24))
print(psutil.Process().memory_info().rss / (20000 * 1024))

1557418.6666666667
3.6502


# Performance measurement of computing processes
<p>allows to compare quality of algorithms in terms of runtime and memory.<br>
<p>This is points into the top of runtime complexity.<br>
In my view measuring actual runtime processes instead of making assumptions about
theoretical complexity is preferable.<br>
The helper functions below measure runtime and memory allocation.</p>

In [1168]:
def timemeasure(func):
    
    """Measures the execution time of a function = func.
    
       Args: an input func.
       
       Returns: the execution time of func."""
    
    # import time
    
    # main function execution_time 
    # the nested inner function measures wraps the main function func 
    # through the outer func execution_time
    def wrapper(*args):
        start_time_555 = time()
        # print("starttime:", start_time)
        # Calling the main_function main()
        output =  func(*args)
        sleep(0.000000001)
        endtime_555  = time()
        # print("endtime:", endtime)
        runtime_555  = endtime_555  - start_time_555 
        # print(execution_time)
        print(f'Runtime: {runtime_555 : .20f} seconds.')
        return output
    return wrapper

In [1169]:
print(timemeasure.__name__)
print("_____________")
print(timemeasure.__doc__)

timemeasure
_____________
Measures the execution time of a function = func.
    
       Args: an input func.
       
       Returns: the execution time of func.


### Monitoring memory usage of a running Python program
<p>This is copied from Geeks.Thanks.<br>
<a href="https://www.geeksforgeeks.org/monitoring-memory-usage-of-a-running-python-program/" target="_blank">Geeks</a> 
</p>

In [1170]:
# importing libraries
# import os
# import psutil
  
# inner psutil function
def process_memory():
    process = psutil.Process(os.getpid())
    mem_info = process.memory_info()
    return mem_info.rss
  
# decorator function
def profile(func):
    def wrapper(*args, **kwargs):
  
        mem_before = process_memory()
        result = func(*args, **kwargs)
        mem_after = process_memory()
        print("{}: Consumed memory: {:,}".format(
            func.__name__,
            mem_before, mem_after, mem_after - mem_before))
  
        return result
    return wrapper

# Data structures

## Arrays & lists
### Creating arrays

In [1171]:
list_1 = np.arange(20,30,1).tolist()
list_1.append(9)

print(list_1)
print(type)
print(len(list_1))

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 9]
<class 'type'>
11


In [1172]:
array_1 = np.array(list_1)
print(array_1)
print(len(array_1))

[20 21 22 23 24 25 26 27 28 29  9]
11


#### Determine the dtype of array elements

In [1173]:
list_223 = list(np.arange(1,10,1))
array_2 = np.array(list_223, dtype=np.dtype('str'))
print(array_2)
print(type(array_2))
print(type(array_2[0]))

['1' '2' '3' '4' '5' '6' '7' '8' '9']
<class 'numpy.ndarray'>
<class 'numpy.str_'>


#### Creating an array

In [1174]:
array_33=np.random.randint(1,10, size=10)
array_333=np.random.randint(100,10000, size=10)
array_444=np.random.randint(444,460, size=10)

array_4=np.array([array_33, array_333, array_444])
print(array_4)
print(type(array_4))
print(np.shape(array_4))

[[   3    4    9    9    3    1    4    9    9    9]
 [5252 9908 1186 2428 3384 6015 2222 6777 4447 6122]
 [ 455  456  448  444  444  458  455  454  444  447]]
<class 'numpy.ndarray'>
(3, 10)


#### Reshaping an array

In [1175]:
array_5=array_4.reshape(10,3)
print(array_5)
print(np.shape(array_5))

[[   3    4    9]
 [   9    3    1]
 [   4    9    9]
 [   9 5252 9908]
 [1186 2428 3384]
 [6015 2222 6777]
 [4447 6122  455]
 [ 456  448  444]
 [ 444  458  455]
 [ 454  444  447]]
(10, 3)


#### Subsetting

In [545]:
array_5[0:4, 1:3] # 0:4 - rows, 1-3 - columns

array([[   8,    3],
       [   5,    9],
       [   1,    8],
       [3378, 6670]])

#### Elementwise processing of math operations

In [1176]:
array_33444 = array_33 + array_444
print(array_33444)
print(np.shape(array_33444))

[458 460 457 453 447 459 459 463 453 456]
(10,)


In [1177]:
array_33444_multi = array_33 * array_444
print(array_33444_multi)
print(np.shape(array_33444_multi))

[1365 1824 4032 3996 1332  458 1820 4086 3996 4023]
(10,)


#### Boolean arrays

In [1179]:
array_33444_multi > 3000

array([False, False,  True,  True, False, False, False,  True,  True,
        True])

#### Filtering based on conditions

In [1180]:
array_33444_multi[array_33444_multi > 3000]

array([4032, 3996, 4086, 3996, 4023])

In [1181]:
np.random.shuffle(list_1) # shuffles in place
print(list_1)
print(len(list_1))

[23, 9, 25, 21, 20, 24, 26, 22, 28, 29, 27]
11


#### Broadcasting
<p>math operations on arrays of different dimensions.<br>
Very important for matrix operations.<br>
Essential for example for deep learning.
</p>

In [1183]:
array_33_3 = array_33 * 3

print(array_33_3)
print(np.shape(array_33))
print(np.shape(array_33_3))

[ 9 12 27 27  9  3 12 27 27 27]
(10,)
(10,)


#### Broadcast error
<p>due to different shapes.<br>
ValueError: operands could not be broadcast together with shapes (3,10) (10,3)</p>

In [1184]:
print(np.shape(array_4))
print(np.shape(array_5))
# array_4 * array_5

(3, 10)
(10, 3)


In [1185]:
# reshaping
array_6 = array_5.reshape(3,10)
array_45_2 = array_4 * array_6.reshape(3,10)
print(np.shape(array_45_2))
print(array_45_2)

(3, 10)
[[       9       16       81       81        9        1       16       81
        81       81]
 [27583504 98168464  1406596  5895184 11451456 36180225  4937284 45927729
  19775809 37478884]
 [  207025   207936   200704   197136   197136   209764   207025   206116
    197136   199809]]


#### Matrix multiplication
<p>works on ground of matrix operation rules, <br>
whereby rows of the first array are multiplicated with cols of the second array.
</p>

In [1187]:
dot_1 = np.dot(array_4, array_5)

print(np.shape(dot_1))
print(dot_1)

(3, 3)
[[   39709    93517   120147]
 [58050575 55789018 85119502]
 [ 5923194  7825538  9824527]]


In [1188]:
dot_2 = np.dot(array_5, array_4)

print(np.shape(dot_2))
print(dot_2[0])

(10, 10)
[25112 43748  8803 13735 17541 28185 12995 31221 21811 28538]


#### Numpy arrays versus list 
<p>when doing element-wise operations.</p>

In [1190]:
list_a56 = [list(np.arange(1,6,1)), list(np.arange(6,11,1))]
print(list_a56)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


#### Multiply every element of this nested list with 17

In [1191]:
# This naive approach does not work
print(len((list_a56*17)))
(list_a56*17)[:4]

34


[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

<p>More code is necessary, while map makes it even comparable easy.</p>

In [1192]:
list_elementwise_55 = list(map(lambda z: [n*17 for n in z],  list_a56))
print(list_elementwise_55)

[[17, 34, 51, 68, 85], [102, 119, 136, 153, 170]]


<p>Elementwise operations on Numpy arrays afford little code,<br>
as arrays are optimized for this other than lists.</p>

In [1193]:
np.array(list_a56) * 17

array([[ 17,  34,  51,  68,  85],
       [102, 119, 136, 153, 170]])

In [1194]:
array_1001 = np.arange(1,21,1)
list_1001 = array_1001.tolist()

print(type(array_1001))
print(type(list_1001))
print(list_1001)

<class 'numpy.ndarray'>
<class 'list'>
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [1195]:
even_numbers_1001 = filter(lambda u: u % 2 == 0, list_1001)
for i in even_numbers_1001:
    print(i)

2
4
6
8
10
12
14
16
18
20


In [1196]:
array_1001[array_1001 % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [1197]:
list_of_lists_3 =\
[np.arange(1,11,1).tolist(), np.arange(11,21,1).tolist(), np.arange(21,31,1).tolist()]

print(len(list_of_lists_3))

3


In [1198]:
[p[:2] for p in list_of_lists_3]

[[1, 2], [11, 12], [21, 22]]

In [1199]:
list_of_lists_100 = [[i*i+100 for i in p] for p in list_of_lists_3 ]
len_list_of_lists_100 = sum([len(i)  for i in list_of_lists_100])
print(len_list_of_lists_100)

30


In [1200]:
list_of_lists_array = \
np.array(list_of_lists_3) * np.array(list_of_lists_3) + 100

print(list_of_lists_array)

[[ 101  104  109  116  125  136  149  164  181  200]
 [ 221  244  269  296  325  356  389  424  461  500]
 [ 541  584  629  676  725  776  829  884  941 1000]]


In [1201]:
print(list_of_lists_100)

[[101, 104, 109, 116, 125, 136, 149, 164, 181, 200], [221, 244, 269, 296, 325, 356, 389, 424, 461, 500], [541, 584, 629, 676, 725, 776, 829, 884, 941, 1000]]


In [1202]:
print(np.shape(list_of_lists_array))
print(np.shape(list_of_lists_array)[0] * np.shape(list_of_lists_array)[1])

(3, 10)
30


### Sorting list with sort
<p> in place. </p>

In [1204]:
list_1.sort()
print(list_1)

[9, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]


In [1205]:
list_2 = np.arange(1000,2000,100).tolist()
list_2.insert(0, 0.98)

print(list_2)
print(type(list_2))
print(len(list_2))

[0.98, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900]
<class 'list'>
11


### Sorting list with sorted
<p> with assignement. </p>

In [1207]:
list_21 = sorted(list_2)

print(list_21)
print(type(list_21))
print(len(list_21))

[0.98, 1000, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900]
<class 'list'>
11


In [1208]:
list_3 = np.arange(0,10,1).tolist()
list_3.insert(0, 0.98)

print(list_3)
print(len(list_3))

[0.98, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
11


#### Remove-method

In [1210]:
list_34 = ["sun", 0, "moon", "star", 49, 67, True]
list_45 = ["sun", 2, "venus", "mars", 122, 67, False]

for element in list_34:
    if element in list_45:
        list_34.remove(element)
        
print(list_34)
print(list_45)

[0, 'moon', 'star', 49, True]
['sun', 2, 'venus', 'mars', 122, 67, False]


#### List comprehensions

In [1211]:
n_list=[n for n in range(1,11)]
print(n_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [1212]:
n_even=[n for n in range(1,11) if n % 2 == 0]
print(n_even)

[2, 4, 6, 8, 10]


In [1213]:
gallico_111 = \
"Caesar, when he Observes this, draws off his Forces to the next Hill, and sent \
the cavalry to sustain the Attack of the Enemy."

gallico_111

'Caesar, when he Observes this, draws off his Forces to the next Hill, and sent the cavalry to sustain the Attack of the Enemy.'

In [1214]:
length_lowercase_words = \
[len(word) for word in re.split(" ", gallico_111) if word.islower()]

print(length_lowercase_words)

[4, 2, 5, 5, 3, 3, 2, 3, 4, 3, 4, 3, 7, 2, 7, 3, 2, 3]


#### Building pairs

In [1216]:
n = [233, 333, 433, 533]
c = ["X", "Y", "Z", "Q"]

pairs = [(i, j) for i in n for j in c]
print(pairs)
print(len(pairs))

[(233, 'X'), (233, 'Y'), (233, 'Z'), (233, 'Q'), (333, 'X'), (333, 'Y'), (333, 'Z'), (333, 'Q'), (433, 'X'), (433, 'Y'), (433, 'Z'), (433, 'Q'), (533, 'X'), (533, 'Y'), (533, 'Z'), (533, 'Q')]
16


In [1217]:
pairs_2 = [[(i, j) for i in n] for j in c]
print(pairs_2)
print(len(pairs_2))

[[(233, 'X'), (333, 'X'), (433, 'X'), (533, 'X')], [(233, 'Y'), (333, 'Y'), (433, 'Y'), (533, 'Y')], [(233, 'Z'), (333, 'Z'), (433, 'Z'), (533, 'Z')], [(233, 'Q'), (333, 'Q'), (433, 'Q'), (533, 'Q')]]
4


In [1218]:
pairs_2 = [(j, i) for i in n for j in c]
print(pairs_2)
print(len(pairs_2))

[('X', 233), ('Y', 233), ('Z', 233), ('Q', 233), ('X', 333), ('Y', 333), ('Z', 333), ('Q', 333), ('X', 433), ('Y', 433), ('Z', 433), ('Q', 433), ('X', 533), ('Y', 533), ('Z', 533), ('Q', 533)]
16


#### Bag of words
<p>
Counting occurrences of words in a text.
</p>

In [1220]:
gallico_4444 =\
"Caesar, when he observes this, draws off his forces to the next hill, and sent the \
cavalry to sustain the attack of the enemy. He himself, meanwhile, drew up on the \
middle of the hill a triple line of his four veteran legions in such a manner, \
that he placed above him on the very summit the two legions, which he had lately \
levied in Hither Gaul, and all the auxiliaries; and he ordered that the whole \
mountain should be covered with men, and that meanwhile the baggage should be \
brought together into one place, and the position be protected by those who were \
posted in the upper line."

gallico_4444_list = re.split(" ", gallico_4444)
print(gallico_4444_list[:4])

['Caesar,', 'when', 'he', 'observes']


In [1221]:
gallico_words = [w.lower() for w in gallico_4444_list]
print(gallico_words[:3])

['caesar,', 'when', 'he']


<p>Unique words in the text.</p>

In [1223]:
gallico_set = set(gallico_words)
print(len(gallico_set))

gallico_set_list = list(gallico_set)
print(gallico_set_list[:5])

76
['this,', 'triple', 'who', 'with', 'should']


<p>Counting the number of occurrences of unique words.</p>

In [1224]:
gallico_tuples = [(w, gallico_words.count(w)) for w in gallico_words]

print(len(gallico_tuples))
print(gallico_tuples[:5])

109
[('caesar,', 1), ('when', 1), ('he', 5), ('observes', 1), ('this,', 1)]


In [1225]:
gallico_dict = dict(gallico_tuples)
dict(itertools.islice(gallico_dict.items(), 6))
# gallico_dict.items()

{'caesar,': 1, 'when': 1, 'he': 5, 'observes': 1, 'this,': 1, 'draws': 1}

In [1226]:
gallico_bag_words = dict()

for k,v in gallico_dict.items():
    if v >1:
        gallico_bag_words[k] = v
        
        
print(len(gallico_bag_words))   
print(gallico_bag_words)

12
{'he': 5, 'his': 2, 'to': 2, 'the': 13, 'and': 5, 'of': 3, 'on': 2, 'a': 2, 'in': 3, 'that': 3, 'should': 2, 'be': 3}


In [1227]:
gallico_bag_words_df=\
pd.DataFrame.from_dict(gallico_bag_words, orient='index', columns=['Occurrences']).\
sort_values(by='Occurrences', ascending=False)

gallico_bag_words_df.head()

Occurrences
the           13
he             5
and            5
of             3
in             3

In [1228]:
n_12 = np.arange(1,20,1)
print(n_12)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [1229]:
n_sqrt = {}
for e, c in enumerate(n_12, 1):
     n_sqrt[e]=math.sqrt(c)

n_sqrt_df = \
pd.DataFrame.from_dict(n_sqrt, orient="index", columns=['sqrt'])

n_sqrt_df['n'] = n_sqrt_df.sqrt**2

n_sqrt_df.head(5)

sqrt    n
1  1.000000  1.0
2  1.414214  2.0
3  1.732051  3.0
4  2.000000  4.0
5  2.236068  5.0

#### Determine prime numbers

In [1231]:
def prime_n(n):
    if n < 2:
        return False
    elif n == 2:
            return True
    for i in range(2, n+1):
        if n % i == 0:
            return False
        return True

In [1232]:
print(prime_n(122))
print(prime_n(177))

False
True


In [1233]:
prime_n= [(n, prime_n(n)) for n in n_12]
prime_n

[(1, False),
 (2, True),
 (3, True),
 (4, False),
 (5, True),
 (6, False),
 (7, True),
 (8, False),
 (9, True),
 (10, False),
 (11, True),
 (12, False),
 (13, True),
 (14, False),
 (15, True),
 (16, False),
 (17, True),
 (18, False),
 (19, True)]

#### Greatest common divisor

In [ ]:
print(24%12)
print(24/12)
print(12%24)

In [ ]:
print(57%3)
print(57/3)
print(3%257)

In [ ]:
print(7%3)
print(7/3)
print(3%7)

In [ ]:
def gcDivisor(a, b):
    while b != 0:
        temp_a = a
        # print(temp_a)
        a = b
        b = temp_a % b    
        # print(b)
    return a

In [ ]:
print(gcDivisor(9, 7))
print(gcDivisor(7, 9))

In [ ]:
print(gcDivisor(9, 7))
print(gcDivisor(7, 9))

#### Coprime numbers

In [ ]:
list1 = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70]
list2 = [7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]

co_prime_numbers=[(i,j) for i in list1 for j in list2 if gcDivisor(i,j) == 1]
print(co_prime_numbers[:5])

#### Creating a letter index

In [ ]:
def create_letter_index(string):
    letter_index = {}
    for idx, letter in enumerate(string):
        if letter in letter_index:
            letter_index[letter].append(idx)
        else:
            letter_index[letter]=[idx]
    
    return letter_index

In [ ]:
gallico_1 =\
"Roman people"

In [ ]:
gallico_index_1 = create_letter_index(gallico_1)
gallico_index_1

#### Move elements

In [ ]:
while len(list_34) < len(list_45):
    move_element = list_45.pop()
    list_34.append(move_element)
    
print(list_34)
print(list_45)

## Dictionaries

In [ ]:
cars_12 = {'Ford':12, 'Toyota':34, 'VW':56, 'Mercedes':23, 'Mazda':15}
print(cars_12)

In [ ]:
print(cars_12.keys())
print(cars_12.values())
print(cars_12.items())

In [ ]:
print(cars_12.get('Toyota'))
print(cars_12['Toyota'])

In [ ]:
cars_12['Tesla']=14
print(cars_12)

In [ ]:
cars_12.popitem()
print(cars_12)

In [ ]:
cars_12.pop('Ford')
print(cars_12)

In [ ]:
cars_12222 = cars_12.copy()
cars_12222.clear()
print(cars_12222)
print(cars_12)

#### Storing the z-values of  circular paraboloid

In [ ]:
range_x = [0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0]
range_y = [0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0]

In [ ]:
circ_parab = dict()

for x in range_x:
    for y in range_y:        
        # Calculate the value for z
        z = x**2 + y**2
        # Create a new key for the dictionary
        key = (x,y)
        # Create a new key-value pair      
        circ_parab[key] = z

#### Slicing the dict

In [ ]:
# import itertools
dict(itertools.islice(circ_parab.items(), 4))

#### Get values

In [ ]:
print(circ_parab[(0.0, 0.6)])

In [ ]:
print(circ_parab[(0.0, 0.2)])

In [ ]:
print(circ_parab[(1.8, 1.4)])

## Sets

In [ ]:
set_1=set(list_2)
print(type(set_1))

set_2=set(list_3)
print(type(set_2))

In [ ]:
print(set_1)
print(len(set_1))

print(set_2)
print(len(set_2))

### Union

In [ ]:
union_1=set_1.union(set_2)
print(union_1)

In [ ]:
union_12 = sorted(union_1)
print(union_12)

In [ ]:
union_2= set_1 | set_2
print(union_2)

In [ ]:
union_21 = sorted(union_2)
print(union_21)

### Intersection

In [ ]:
intersection_1 = set_1.intersection(set_2)
print(intersection_1 )

In [ ]:
intersection_2 = set_1 & set_2
print(intersection_2)

In [ ]:
set_1.isdisjoint(set_2)

<p>False means the set are not disjointed and have an intersection.</p>


### Difference
#### symmetric_difference
<p>returns all elements in set1 and set2, but not in both.</p>

In [ ]:
sym_1 = set_1.symmetric_difference(set_2)

print(sym_1)
print(len(sym_1))

In [ ]:
set_13 = set_1.copy()
print(type(set_13))
print(set_13)

In [ ]:
set_13.symmetric_difference_update(set_2)

print(set_1)
print(set_2)
print(sorted(set_13))

#### difference
<p>returns all elements in set2 different to set1.

In [ ]:
diff_1 = set_1.difference(set_2)

print(diff_1)
print(len(diff_1))

In [ ]:
list_4 = np.random.randint(0,100,20).tolist()
list_5 = np.random.randint(0,100,20).tolist()

In [ ]:
print(list_4)
print(list_5)

### Set theory
<p>
Problem:<br>
A_union (B_intersection_C) difference D_intersection_E
</p>

In [ ]:
list_4 = list(np.arange(1,10,1))
list_5 = list(np.arange(2000,3000,100))

list4_sorted = sorted(list_4)
list5_sorted = sorted(list_5)

In [ ]:
set_4 = set(list4_sorted)
set_5 = set(list5_sorted)

print(type(set_4))
print(type(set_5))

In [ ]:
A = {1, 2, 3, 4, 5, 6, 7}
B = {5, 7, 9, 11, 13, 15}
C = {1, 2, 8, 10, 11, 12, 13, 14, 15, 16, 17}
D = {1, 3, 5, 7, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}
E = {9, 10, 11, 12, 13, 14, 15}

print(A)

In [ ]:
intersection_5 = set_4.intersection(set_5)
print(intersection_5)

In [ ]:
B_intersection_C = B.intersection(C)
print(B_intersection_C)

In [ ]:
A_union_B_intersection_C = A.union(B_intersection_C)
print(A_union_B_intersection_C)

In [ ]:
D_intersection_E = D.intersection(E)
print(D_intersection_E)

In [ ]:
A_union_B_intersection_C_D_intersection_E=\
A_union_B_intersection_C.difference(D_intersection_E)
A_union_B_intersection_C_D_intersection_E

### Iterables

In [ ]:
range_1 = range(0,5)
for i in range_1:
    print(i)

In [ ]:
countries=['Germany', 'USA', 'Mongolia', 'Zimbabwe', 'Kenia', 'Chile', 'Paraguay']
countries_enumerated = enumerate(countries)

for idx, country in countries_enumerated:
      print(str(idx)+ " - " + country)

#### Is iterable object?

In [ ]:
iter(countries)

In [ ]:
iter("carwash")

In [ ]:
countries_2_iter=iter(countries)

print(next(countries_2_iter))
print(next(countries_2_iter))
print(next(countries_2_iter))
print(next(countries_2_iter))

#### Creating a letter index

In [ ]:
def create_letter_index(string):
    letter_index = {}
    for idx, letter in enumerate(string):
        if letter in letter_index:
            letter_index[letter].append(idx)
        else:
            letter_index[letter]=[idx]
    
    return letter_index

In [ ]:
gallico_1 =\
"Roman people"

In [ ]:
gallico_index_1 = create_letter_index(gallico_1)
gallico_index_1

#### Iterrows over data frames

In [ ]:
dict_countries=\
{'Germany':[80000000, 'Europe', 1.05], 'China':[1411778724, 'Asia', 17.9],
'Brazil':[213843297, 'Americas', 2.71]}

df_countries = pd.DataFrame(dict_countries, index=['Population', 'Region', '% of world'])

df_countries 

In [ ]:
countries_iter = df_countries.iterrows()

for idx, c in countries_iter:
    print(idx)
    print(c)
    print(type(c))

In [ ]:
terror=pd.read_csv("csv/france_terrorism_fatalities_by_year.csv")
terror.head()

In [ ]:
terror_iter = terror.iterrows()
terror_dict = dict()
for idx, incident in terror_iter:
    terror_dict[idx] = [incident]
    
# slicing a dict
dict(itertools.islice(terror_dict.items(), 3))

#### Iteritems over data frame
<p>
gives the columns.
</p>

#### Terror dataset

In [ ]:
terror_items = terror.head().iteritems()

terror_name=[]
terror_iteritems=[]
for name, item in terror_items:
    terror_iteritems.append(item)
    terror_name.append(name)
    
print(terror_iteritems[0])
print(f"Type: {type(terror_iteritems[0])}")

print(terror_name)
print(f"Type: {type(terror_name)}")

#### Heroes dataset

In [ ]:
heroes=pd.read_csv('csv/heroes_information.csv')
heroes=heroes.select_dtypes(include="object")
heroes.info()

In [ ]:
heroes.head(2)

#### Creating a value counts for every categorical variable
<p>
The categorical variables are described by the column name.<br>
For example the number of occurrences for the eye color blue are counted.
</p>

In [ ]:
column_counts = dict()

for column_name, series in heroes.iteritems():
    # Retrieve the values stored in series in a list for
    values = list(series)
    category_counts = dict()  
    # Traverse through unique categories in values
    for category in set(values):
        # Count the appearance of category in values
        category_counts[category] = values.count(category)
    
    column_counts[column_name] = category_counts

In [ ]:
heroes_names = pd.DataFrame.from_dict(column_counts['Eye color'], orient='index', 
                                      columns=['Eye color'])
heroes_names = heroes_names.sort_values(by='Eye color', ascending=False)

heroes_names.info()

In [ ]:
heroes_names.describe()

In [ ]:
heroes_names.head()

#### Zipping iterable objects

In [ ]:
iter_n5=np.arange(1,6,1)
iter_heroes5 = ['Mr.Fantastic', 'Spiderman', 'Ironman', 'Captain', 'Antman']
iter_string5 = 'XTeam'

In [ ]:
zipp_1 = zip(iter_n5, iter_heroes5, iter_string5)
print(zipp_1)

In [ ]:
for i in zipp_1:
    print(i)

In [ ]:
zipp_2 = zip(iter_n5, iter_heroes5, iter_string5)

print(next(zipp_2))
print(next(zipp_2))
print(next(zipp_2))

#### Reversing iterables

In [ ]:
seq100 = np.arange(10,100,10)
reversed_seq = reversed(seq100)

reversed_seq_dict = {}

for x,y in zip(reversed_seq, seq100):
    reversed_seq_dict[y] = x
        
reversed_seq_dict

#### Reverse pairing (unpair)

In [ ]:
forms = [('triangle', 1) , ('circle', 2)]
print(forms)

forms_zip = zip(*forms)
forms_unpair=[i for i in forms_zip]
print(forms_unpair)

In [ ]:
out = list(itertools.chain(*forms_unpair))
print(out)

#### Dict from tuples

In [ ]:
dict(forms)

#### Dict from zip

In [ ]:
keys=['number', 'colors', 'animal']
values=[[100,200,300], ['red', 'blue', 'green'], ['bear', 'cow', 'cat']]

d_123 = dict(zip(keys, values))
d_123

In [ ]:
pd.DataFrame(d_123)

In [ ]:
def max_len_word(io):
    max_len_word=" "
    for word in io:
        if len(max_len_word) < len(word):
            max_len_word = word
    return max_len_word

In [ ]:
g_334=\
"The Helvetii having followed with all their wagons, collected \ \
their baggage into one place.".split()
print(g_334)

g_455=\
"Being on the same day informed by his scouts, that the enemy had encamped at the foot \
of a mountain eight miles from his own camp.".split()

g_477=\
"Publius Considius, who was reputed to be very experienced in military affairs \
is sent forward with the scouts.".split()

In [ ]:
print(max_len_word(g_334))
print(max_len_word(g_455))
print(max_len_word(g_477))

In [ ]:
g_list = [g_334, g_455, g_477]
print(len(g_list))

In [ ]:
g_lengths=[len(l) for l in g_list]
g_lengths

In [ ]:
g_max_words = [max_len_word(l) for l in g_list]
g_max_words 

In [ ]:
for i in zip(g_list, g_lengths, g_max_words):
    print(i)

#### Creating a df from a zip object

<p>follows the workflow list/array to zip to dict df.</p>

In [ ]:
array_33 = np.arange(333, 933, 100)
array_77 = np.arange(1077, 1677, 100)

print(len(array_33))
print(len(array_77))

In [ ]:
array_tuple_1 = [(i,t) for i in array_33 for t in array_77]

print(array_tuple_1[:10])
print(type(array_tuple_1))

In [ ]:
array_1, array_2 = zip(*array_tuple_1)

print(array_1[:10])
print(type(array_1))
print(len(array_1))

print("____________________________________________________________")
print(" ")

print(array_2[:10])
print(len(array_2))
print(type(array_2))

In [ ]:
column_names = ['array_1', 'array_2']
zip_obj = zip(['array_1', 'array_2'], [array_1, array_2])
print(zip_obj)

In [ ]:
dict_12 = dict(zip_obj)
df_12 = pd.DataFrame(dict_12)

In [ ]:
df_12.head()

#### Generator objects
<p>
or special customized iterable objects created by a func.<br>
Using the next function to ouputt without occupying more memory.<br>
Producing infinite amount of output elements with gen obj.<br>
The yield instead of the return statement indicates a generator object.<br>

</p>

In [ ]:
def multiple_yields():
    yield 1
    yield 2
    yield 3

In [ ]:
# Print obj adress in memory
print(multiple_yields())

# Read with next
iter_multiple_yields = multiple_yields()
print(next(iter_multiple_yields))
print(next(iter_multiple_yields))
print(next(iter_multiple_yields))

# With list constructor
print(list(multiple_yields()))
print(list(multiple_yields()))

In [ ]:
def yield_test(n):
    for i in range(20,26):
        yield i**3

In [ ]:
yield_1 = yield_test(7)
yield_1_list = list(yield_1)

print(yield_1)
print(yield_1_list)


#### Generator comprehension
<p>using round brackets.</p>

In [ ]:
output_gen = (i**3 for i in range(222,229))

for e in output_gen:
    print(e)

print(output_gen)
print(list(output_gen))

<p>
All generator obj are expendable.<br>
A second traversal does not yield any result.<br>
The output remains empty.</p>
</p>

In [ ]:
print(list(output_gen))

In [ ]:
def every_number(n):
    while True:
        yield n

In [ ]:
every_number_genobj = every_number(5)

print(every_number_genobj)
next(every_number_genobj)
next(every_number_genobj)

#infinite output
# for i in every_number_genobj:
    # print(i)

#### Generator functions versus gen comprehensions

In [ ]:
def foo_1000(num):
    for i in range(0,num):
        yield i + 111

foo_1000_gen = foo_1000(1000)

foo_1000_gen_list = []
for i in foo_1000_gen:
        foo_1000_gen_list.append(i)
    
print(foo_1000_gen_list[:10])

In [ ]:
foo_1000_gen_2 = (i + 111 for i in range(0,1000))

foo_1000_gen_list_2 = []
for i in foo_1000_gen_2:
        foo_1000_gen_list_2.append(i)
    
print(foo_1000_gen_list_2[:10])

In [ ]:
foo_1000_gen_3 = (i + 0.11 for i in np.arange(0.1,10.1,0.1))

foo_1000_gen_3_list=[]
for i in foo_1000_gen_3:
    foo_1000_gen_3_list.append(i)

print(len(foo_1000_gen_3_list))
print(foo_1000_gen_3_list[:10])

#### Shifting elements of an obj using a genobj

In [ ]:
i = "widgetfactory"
len_obj = len(i)
output_widget = []
for idx in range(0, len_obj):
        j = i[(idx + 2) % len_obj]
        output_widget.append(j)

output_widget

In [ ]:
output_widget_str = ""

for i in output_widget:
    output_widget_str += output_widget_str.join(str(i))

print(output_widget_str)

In [ ]:
def shift_iterable(i, shift):
    len_obj = len(i)
    for idx in range(0, len_obj):
        yield i[(idx + shift) % len_obj]

In [ ]:
shift_iterable_listn = list(shift_iterable(np.arange(1,10,1), shift=2))

print(np.arange(1,10,1))
print(shift_iterable_listn)

In [ ]:
shift_iterable_string = list(shift_iterable("swimmingpool", shift=2))

print("swimmingpool")
print(shift_iterable_string)

In [ ]:
total, out = 0, dict([(i, [0, 0]) for i in range(1, 7)])
print(total)
print(out)
print(out[2][0])
print(out[5][0])
print(out[5])

In [ ]:
import random
def simulate_dice_throws():
    while True:
        # Simulate a single toss to get a new number
        num = random.randint(1, 6)
        total += 1
        # Update the number and the ratio of realizations
        # print(num)
        out[num][0] = num
        # print(out[num][0])
        yield out

In [ ]:
import random

random.seed(42)

num = random.randint(1, 2)
print(num)

num_2 = random.randint(1,6)
print(num_2)

print(np.arange(1,7,1))


### Using a counter

In [ ]:
print(list4_sorted)
print(list5_sorted)

In [ ]:
set_4 = set(list4_sorted)
set_5 = set(list5_sorted)

print(type(set_4))
print(type(set_5))


In [ ]:
print(sorted(set_4))
print(sorted(set_5))

In [ ]:
zip_1 = zip(list4_sorted, list5_sorted)

In [ ]:
counter = 0

for i, (a,b) in enumerate(zip_1):
    if counter <= 4:
        print(f'{i}: list 4: {a}')
        print(f'{i}: list 5: {b}')
        counter += 1
    else:
        break

In [ ]:
print(counter)

#### Creating a timer for measuring runtime of functions

#### Intersection with for loop using the in operator

In [ ]:
start_1=time()
intersection_list_1 = []
for a in list4_sorted:
    # print(a)
    if a in list5_sorted:
        intersection_list_1.append(a)

end_1=time()
run_1= (end_1-start_1)

print(f'Runtime: {run_1} seconds.')

In [ ]:
intersection_list_1 == list(sorted(intersection_5)) 

In [ ]:
print(intersection_list_1)
print(sorted(intersection_5))

In [ ]:
@timemeasure
@profile
def inter_in(l1, l2):
    l1 = sorted(l1)
    l2 = sorted(l2)
    intersection_in = []
    for a in l1:
        if a in l2:
            intersection_in.append(a)
    return intersection_in

In [ ]:
inter_in_55 = inter_in(list4_sorted, list5_sorted)
print(inter_in_55)

#### Intersection with for loop using a counter

In [ ]:

start_2=time()
counter_2 = 0
inter_3 = []


for e in list4_sorted:
    if e == list5_sorted[counter_2]:
        inter_3.append(e)
        counter_2 += 1
    else:
        continue

sleep(0.000000001)
end_2=time()
run_2= (end_2-start_2)

print(f'Runtime: {run_2: .20f} seconds.')


In [ ]:
print(inter_3)
print(inter_3 == sorted(intersection_5))

#### Intersection with parallel for loops on sorted lists

In [ ]:
start_3 = time()
intersect_4 = []

for x in list4_sorted:
    for y in list5_sorted:
        if x==y:
            intersect_4.append(x)
sleep(0.000000001)
end_3 = time()
run_3 = end_3 - start_3
print(f'Runtime: {run_3} seconds.')            

print(intersect_4)            

## Functions

In [ ]:
def put_together(*args):
    str_obj=""
    for arg in args:
        str_obj += " " + arg
    return str_obj

put_together_1 = put_together("Caesar", "passes", "the", "Rubicon.")
print(put_together_1)
print(type(put_together_1))

In [ ]:
def foo_args_add(*args):
            output = 0
            for arg in args:
                output += arg
            return output


foo_args_add(1,2,3,4,5,6)

#### Using *args with an iterator object

In [ ]:
numbers_6 = (1,2,3,4,5,6)
print(type(numbers_6))

numbers_6_iter = foo_args_add(*numbers_6)
print(numbers_6_iter)

#### Check datatypes

In [ ]:
def check_dtypes(*args):
    dtypes=dict()
    
    for value in args:
        if isinstance(value, (int, float, complex)):
                      dtypes['number']=value
        elif isinstance(value, str):
                      dtypes['string']=value
        elif isinstance(value, bool):
                      dtypes['bool']=value
        elif isinstance(value, (list, tuple, range)):
                      dtypes['sequence']=value
        # And so on: dict, set
        else:
            dtypes['Unknown']=value
    return dtypes

In [ ]:
check_dtypes("sunshine", 123, True, 1667.5, [1,2,3], bytearray(5))

In [ ]:
def is_capital(l):
    capital_dict = {'Lower':list(), 'Upper':list()}
    for arg in l:
        # print(arg[0])
        if arg[0].islower() == True:
            capital_dict['Lower'].append(arg)
        elif arg[0].isupper() == True:
            capital_dict['Upper'].append(arg)
    return capital_dict

In [ ]:
saone_split=\
"There is a river called the Saone , which Flows through the territories of \
the Aedui and Sequani into the Rhone with such Incredible slowness, that it can \
not be Determined by the eye in which Direction it flows.".split(" ")
print(saone_split)

In [ ]:
is_capital_1=is_capital(saone_split)


print(len(is_capital_1['Upper']))
print(len(is_capital_1['Lower']))

#### Kwargs
<p>
with dicts as input arguments.
</p>

In [ ]:
def foo_kwargs(**kwargs):
    print(kwargs)
    
foo_kwarg_1 = foo_kwargs(arg_1=10, arg_2=677, arg_3=8999)

print(foo_kwarg_1)
print(type(foo_kwarg_1))

In [ ]:
def foo_kwargs_add(**kwargs):
            output = 0
            for key, value in kwargs.items():
                output += value
            return "Result: "+ str(output)
        
foo_kwargs_add_1=foo_kwargs_add(num_1=1,num_2=2,num_3=3,num_4=4,num_5=5,num_6=6)

print(foo_kwargs_add_1)
print(type(foo_kwargs_add_1))

In [ ]:
def foo_kwargs_add_dict(**kwargs):
                output=dict()
                for key, value in kwargs.items():
                    output[key]=value
                return output
            
foo_kwargs_add_2=foo_kwargs_add_dict(num_1=1,num_2=2,num_3=3,num_4=4,num_5=5,num_6=6)
print(foo_kwargs_add_2)
print(type(foo_kwargs_add_2))

#### Dicts and append to list

In [ ]:
legions_leaders = {'Legion V':['Maximus'], 'Legion III':['Marc Anton']}
print(legions_leaders)

legions_leaders['Legion III'].append('Cleopetra')
print(legions_leaders)

In [ ]:
def assign_to_type(**kwargs):
    dict_type = {}
    for key, value in kwargs.items():
        if type(value) in dict_type.keys():
            # print(value)
            dict_type[type(value)].append(value)
        else:
            dict_type[type(value)] = [value]
    return dict_type

In [ ]:
assign_to_type(k_1='pavement', k_2=True, k_3=1212.12, k_4=444, 
               k_5=5676, k_6='border', k_7=False)

### Lambda functions
<p>or short-one-in-line functions.<br>
Those have no name and are therefore anonymous.<br>
Used for small tasks or callbacks.</p>

In [ ]:
x1=5
x2=10

lambda x1, x2: x1*x2+x1

In [ ]:
lambda_output_1 = lambda x1, x2: x1*x2+x1
print(lambda_output_1)

In [ ]:
calc_lambda = lambda x1, x2: x1*x2+x1
calc_lambda(x1, x2)

In [ ]:
y1=5
y2=10

def calc_selfdefined_func(y1, y2):
    return y1*y2+y1

calc_selfdefined_func(y1, y2)

#### Calling a lambda function directly

In [ ]:
(lambda x: x1*10+x1)(5)

In [ ]:
def odd_or_even_n(n):
    if n % 2 == 0:
        return ("The number is even.")
    else:
        return ("The number is odd.")

print(odd_or_even_n(177))
print(odd_or_even_n(1344))

#### Ternary operators
<p> are if-else expressions within a function.</p>

In [ ]:
def odd_or_even_2(n):
    return "N is even." if n % 2 == 0 else "N is odd."

print(odd_or_even_2(177))
print(odd_or_even_2(1344))

In [ ]:
print((lambda n: "even" if n % 2 == 0 else "odd")(177))
print((lambda n: "even" if n % 2 == 0 else "odd")(1344))

In [ ]:
print(math.factorial(4))
print(4*3*2)

In [ ]:
conditional_factorial = lambda x: math.factorial(x)  if x > 0 else 'Error'

print(conditional_factorial(10))
print(conditional_factorial(-0))

#### List comprehensions in lambda func

In [ ]:
# Take a list of integers nums and leave only odd numbers
odd_n = lambda nums: [x for x in nums if x % 2 !=0]
print(odd_n(np.arange(1,20,1)))

#### Finding shared letters in two strings

In [ ]:
shared_letters = \
lambda s1, s2: [i for i,j in zip(s1, s2) if  i in s2 or j in s1]


print(shared_letters('Rhine', 'Rhone'))
print(shared_letters('Garonne', 'Pyrenaean'))

In [ ]:
shared_letters_2 = \
lambda s1, s2: [i for i,j in zip(set(s1), set(s2)) if  i in s2]


print(shared_letters_2('Rhine', 'Rhone'))
print(shared_letters_2('Garonne', 'Pyrenaean'))

In [ ]:
intersection_letters = lambda s1, s2: set(s1).intersection(set(s2))

print(intersection_letters('Rhine', 'Rhone'))
print(intersection_letters('Garonne', 'Pyrenaean'))

In [ ]:
nums_110=np.random.randint(100,size=10)
print(nums_110)

lambda3 = lambda nums: math.sqrt(sum([x**2 for x in nums]))
print(lambda3)

nums_110_output = lambda3(nums_110)
print(nums_110_output)



In [ ]:
nums_110=np.random.randint(100,size=10)
print(nums_110)

lambda4 = lambda *nums: math.sqrt(sum([x**2 for x in nums]))
print(lambda4)

nums_34_output = lambda4(3,4)
print(nums_34_output)

#### Lambda and dicts

In [ ]:
def counting_letters(string):
    d = dict()
    for c in set(string):
        d[c] = string.count(c)

    return d

In [ ]:
# First we make a tuple then convert it to a dict
counting_letters_lambda = \
lambda string: dict([(c, string.count(c)) for c in set(string)])

In [ ]:
Garonne_1=\
"The river Garonne"

print(counting_letters(Garonne_1))
print(counting_letters_lambda(Garonne_1))

#### Using a lambda expression as an argument in a function
<p>if the function allows function or lambda arguments<br>
In this case sort allows this within the argument key.<br>
No need to use apply here.</p>

In [ ]:
# From W3 tutorials
cars = ['Ford', 'Mitsubishi', 'BMW', 'VW']

cars.sort()
print(cars)

In [ ]:
def myFunc(e):
    return len(e)

cars = ['Ford', 'Mitsubishi', 'BMW', 'VW']

cars.sort(key=myFunc)
print(cars)

#### This turn the user def func into a lambda

In [ ]:
cars_2 = ['Ford', 'Mitsubishi', 'BMW', 'VW']
lambda_len=lambda e: len(e)
cars_2.sort(key=lambda_len, reverse=True)
cars_2

#### Sort by the last character 
<p>Seems not work.</p>

In [ ]:
cars_3 = ['Ford', 'Mitsubishi', 'BMW', 'VW', 'AA' , 'ZZ']
cars_3.sort(key=lambda s: s[-1])
print(cars_3)

#### Sort words by the total amount of occurrences of certain characters

In [ ]:
cars_4 = ['Ford', 'Mitsubishi', 'BMW', 'VW', 'iiiiiiibbbbbwwww', 'aaa']
cars_4.sort(key=\
            lambda w: sum([w.count('i'), w.count('b'), w.count('w')]), reverse=True)
print(cars_4)

### Map, filter, reduce

<p>are functions under the functional programming paradigm in Python.<br>
Python follows the OOP paradigm.<br>
Of the many implications it is interesting that control statments like
for loops are substituted, when iterables, especially lists, are processed.<br>
<a href="https://www.tutorialspoint.com/functional-programming-languages" target="_blank">tutorialspoint</a> 
</p>

### Map
<p>maps a function to iterables.<br>
It replaces a foor loop.<br>
The map output is an iterator, too.</p>

In [ ]:
map_lambda_1 = lambda n: round(math.sqrt(n),4)

In [ ]:
def map_sqrt(n):
    return round(math.sqrt(n),4)

In [ ]:
map_numbers = list(np.arange(100,1000,50))
map_output_1 = map(map_sqrt, map_numbers)

print(map_output_1)
print(next(map_output_1))
print(next(map_output_1))
print(list(map_output_1))

In [ ]:
map_output_2 = map(map_lambda_1, map_numbers)

print(map_output_2)
print(list(map_output_2))

In [ ]:
n_map_12 = np.arange(20,30,1)
n_map_15 = np.random.randint(1,50, 10)
lambda_map_multiply_pairwise = (lambda x,y: x*y)

map_output_2 = map(lambda_map_multiply_pairwise, n_map_12, n_map_15)

print(list(map_output_2))
print(n_map_12 * n_map_15)

### Filter

<p>filters an iterable and returns only values matchting a condition.
</p>

In [ ]:
filter_iterable = list(np.random.random(5))
filter_output_1 = filter(lambda x: x <= 0.5, filter_iterable)
list(filter_output_1)

#### The above filter func is comparable to the func below:

In [ ]:
f=[]
for i in filter_iterable:
    if i <= 0.5:
        f.append(i)

print(f)

#### Exclude all the numbers from nums divisible by 6 or 10

In [ ]:
np.random.seed=45
nums=np.random.randint(1000,2000, 500)
print(len(nums))

In [ ]:
nums_output = filter(lambda x: x % 6 != 0 or x % 10 != 0, nums)
print(list(nums_output)[450:455])

In [ ]:
nums_output_2 = filter(lambda x: x % 6 != 0 or x % 10 != 0, nums)
print(len(list(nums_output_2)))

In [ ]:
print(1019 % 6)
print(1905 % 10)

#### Returning all consonants from a string

In [ ]:
string_23432 = \
"Divitiacus, embracing Caesar, begins to implore him, with many tears, that \
he would not pass any very severe sentence upon his brother."

consonants = "bcdfghjklmnpqrstvwxyz"
getting_consonants  = filter(lambda x: x in consonants, string_23432)


print(' '.join(getting_consonants))

#### Returning words with more than one character e

In [ ]:
reo = \
"It's more than a feeling (more than a feeling) \
When I hear that old song they used to play (more than a feeling) \
I begin dreaming (more than a feeling)".split()

print(reo)

In [ ]:
more_than_a_feeling = filter(lambda x: x.count('e') > 1, reo)
print(list(more_than_a_feeling))

### Reduce
<p>applies a funct to pairs of values within an iterable.<br>
It compares the value pairs and returns the value matching a condition stepwise.<br>
A more complex definition is given here:</p>

<p>
"Python’s reduce() is a function that implements a mathematical technique called folding or reduction. reduce() is useful when you need to apply a function to an iterable and reduce it to a single cumulative value. Python’s reduce() is popular among developers with a functional programming background, but Python has more to offer."<br>
<a href="https://realpython.com/python-reduce-function/" target="_blank">realpython</a> 
</p>


In [ ]:
np.random.seed=45
reduce_list_1 = np.random.randint(1, 50, 20)
print(reduce_list_1)
print(max(reduce_list_1))

#### Same with reduce

In [ ]:
from functools import reduce
reduce_max = lambda x,y: x if x > y else y
reduce(reduce_max, reduce_list_1)

In [ ]:
print(10 % 5)
print(8 % 3)

#### Determine the same numbers in all sets

In [ ]:
np.random.seed=467

set_110 = list(np.random.randint(11,size=10))
set_111 = set(np.random.randint(11,size=10))
set_112 = set(np.random.randint(11,size=10))
set_113 = set(np.random.randint(11,size=10))

print(set_110)
print(set_111)


In [ ]:
sets = [set_111, set_112, set_113]
intersection_444 = reduce(lambda x,y: x.intersection(y), sets)
print('The same numbers in every set are: ' + str(intersection_444))

#### Output the sum of a number sequence

In [ ]:
sequence = [100, 777, 888, 1111]
sum_output = reduce(lambda x,y: x+y, sequence)
print('The sum of: ' + str(sequence) + ' is: ' + str(sum_output) + '.')

#### Convert numbers to a single string

In [ ]:
numbers = [100, 777, 888, 1111]
num = reduce(lambda x,y: str(x)+str(y), numbers)
print(str(numbers) + ' is combined to a string number ' + str(num) + '.')

#### Spell a string backwards

In [ ]:
string_12 = "De bello gallico"
inverted_string=reduce(lambda a,b: b+a, string_12)
print(inverted_string)

### Recursion
<p>of a function, which calls itself.<br>
A more deeper look is given here:</p> 

<p>
"A recursive definition is one in which the defined term appears in the definition itself."<br>
<a href="https://realpython.com/python-recursion/" target="_blank">realpython</a> 
</p>

In [ ]:
print(5*4*3*2)
print(math.factorial(5))
print(5*math.factorial(5-1))
print(5*24)
print(reduce(lambda x,y: x*y, [5,4,3,2]))


In [ ]:
for n in range(1,5):
    print(n)

#### Factorial with a user-defined func

In [ ]:
def factorials_matter(n):
    # 0 times n is always 0, therefore n = 1
    output = 1
    outputs = {}
    # n+1, because range(1,n) drops the last element of the sequence
    for n in range(1,n+1):
        output *= n
        outputs[n]=output
    return output, outputs

fact_45, fact_list_45 = factorials_matter(5)
print(fact_45)
print(fact_list_45)

<p>Recursion needs a base case or stopping criterion for avoiding infinite loops.</p>

In [ ]:
# Thanks to https://realpython.com/python-recursion/
def countdown(n):
    print(n)
    # base case or stopping criterion
    if n == 0:
        return
    else:
        countdown(n-1)

countdown(n-1)

In [ ]:
def factorials_recursed(n):
    # base case or stopping criterion
    if n == 1:
        return 1
        
    return n*factorials_recursed(n-1)
        
print(factorials_recursed(5))
print(factorials_recursed(1))
print(factorials_recursed(1))

In [ ]:
def real_factorial(n):
    return 1 if n <= 1 else n * real_factorial(n - 1)

real_factorial(5)

### Comparing the runtime performance of different functions
<p>Min, max, diff</p>

In [ ]:
print([run_1, run_2, run_3])
print(max([run_1, run_2, run_3]))
print(min([run_1, run_2, run_3]))

diff_12 = max([run_1, run_2, run_3]) - min([run_1, run_2, run_3])
print(f'Difference between min and max runtime is: {diff_12}.')

### Missing number base problem

<p>A number is missing from a sequence.</p>
<p>
In this base version of the missing number problem, whe have a sequence of 4 numbers.<br>
We identify the missing number not by code like above, but by deductive thinking.<br>
The solution here is not generalizable.<br>
For example it would be time consuming to find the missing number this way in a sequence of 10.000.000.
</p>

In [ ]:
sequence_1 = [2,3,1,5]
print(sequence_1)

In [ ]:
sequence_2 = sorted(sequence_1)
print(sequence_2)

<p>We recognize this is a sequence of integers with change of 1.<br>
Matching every number x aligned with this pattern with the number n in the sequence,<br>
can indicate the missing number.
The missing number is 4.</p>

In [ ]:
@timemeasure
@profile
def find_missing_1(x, sequence):
    for x in range(1, 6):
        if x in sequence:
            print(f"Found: {x}")
        else:
            print(f"Not found: {x}")

In [ ]:
find_missing_1(4, sequence_2)

In [ ]:
5 in np.array(sequence_1)

In [ ]:
def find_missing_in(x, s):
    if x in np.array(s):
        print(True)
    

In [ ]:
find_missing_in(1, sequence_1)

#### The restaurant analogy.
<p>There five people paying a certain amount per person.</p>

In [ ]:
amounts_actual_45 = sequence_2.copy()
print(amounts_actual_45)

In [ ]:
sum_amounts_should = sorted(np.insert(amounts_actual_45, 4, 4))
print(sum_amounts_should)

sum_should = np.sum(sum_amounts_should)
print(sum_should)

In [ ]:
amounts_actual_sum = np.sum(amounts_actual_45)
print(amounts_actual_sum)

In [ ]:
diff_123 = sum_should - amounts_actual_sum 
print(diff_123)

In [ ]:
sum_123 = 0
for i in range(1, len(amounts_actual_45) + 1):
    sum_123 = sum_123 + 1
    
print(sum_123)

In [ ]:
@timemeasure
@profile
def solution_22(seq):
    act_sum_88 = 0
    for number in seq:
        act_sum_88 += number
    max_n = len(seq) + 1
    # print(act_sum_88)
    exp_sum_88 = ((max_n * (max_n + 1)) // 2)
    # print(exp_sum_88)
    return exp_sum_88 - act_sum_88

In [ ]:
sol66 = solution_22( [1, 3, 6, 4, 1, 2])
print(sol66)

In [ ]:
sol1 = solution_22([1,2,3,5])
print(sol1)

In [ ]:
print(np.sum([12,14,15,16]))
sol2 = solution_22([12,13,15,16])
print(sol2)

<p>The above solution makes a lot of assumptions and seems viable only with a small squence.<br>
Can the missing number be detected with coding?</p>

### Missing number problem 1
<p>Data preparation: creating a problem of the missing number 3.</p>

In [ ]:
array_2 = np.arange(0,20,1)
print(array_2)

In [ ]:
index_3 = np.where(array_2 == 3)
print(index_3)

In [ ]:
array_3 = np.delete(array_2, index_3)
array_3_list = array_3.tolist()

print(array_3_list)
print(len(array_3_list))

#### Solution
<p>Step by step solution by doing.</p>

#### First question:<br> What is the missing number?
<p>If the sequence is based on a pattern, the missing number breaks the pattern.<br>
The difference between numbers is such a pattern.<br>
Numpy calculates differences:</p>

In [ ]:
diff_1 = np.diff(array_3_list)

print(diff_1)
print(len(diff_1))

<p>Core python solution.</p>

In [ ]:
diff_12 = []
for i in range(0, len(array_3_list) - 1):
    # print(i)
    # print(array_3_list[i + 1])
    
    # diff_12.append(i)
    diff = array_3_list[i + 1] - array_3_list[i]
    diff_12.append(diff)

print(diff_12)
print(len(diff_12))

<p>Missing number is at index 2, because there the diff pattern is broken.<br>
The difference is 2 instead 1.</p>

In [ ]:
diff_12_array = np.array(diff_12)
deviation_1 = np.where(diff_12_array > 1)

print(deviation_1)
print(type(deviation_1))

print(deviation_1[0])
print(type(deviation_1[0]))


In [ ]:
print(diff_12_array[deviation_1])

In [ ]:
deviation_int = deviation_1[0].item()

print(type(deviation_int))
print(deviation_int)

In [ ]:
print(array_3)
print(type(array_3))

#### Answer: the missing number is:

In [ ]:
missing_value_3 = array_3[deviation_1] + 1
print(missing_value_3)

#### Adding the missing number to the sequence.

In [ ]:
array_4 = np.insert(array_3, deviation_int + 1, missing_value_3)

print(len(array_4))
array_4

<p>Just checking.</p>

In [ ]:
np.diff(array_4)

### Missing number problem 2: <br>finding missing number in a sequence i*3
#### First question:<br> What is the missing number?
#### Preparing the array

In [ ]:
array_times_3 = [i*3  for i in np.arange(0,20,1)]
array_times_3_array = np.array(array_times_3)

print(type(array_times_3_array))
print(type(array_times_3))
print(len(array_times_3))
print(array_times_3)

In [ ]:
np.where(array_times_3==42)

In [ ]:
index_4_breaking = np.where(array_times_3_array==42)
array_times_3_broken = np.delete(array_times_3, index_4_breaking)
array_45 = array_times_3_broken.copy()

print(index_4_breaking)
print(len(array_times_3_broken))
print(type(array_times_3_broken))
print(array_times_3_broken)

<p>Just checking.</p>

In [ ]:
array_times_3_broken[array_times_3_broken == 42]

### Solution
<p>Finding differences in pattern.</p>

In [ ]:
diff_intact = np.diff(array_times_3)
diff_broken = np.diff(array_times_3_broken)

print(diff_intact)
print(diff_broken)

#### Finding the most frequent number and index.

In [ ]:
diff_intact_unique = np.unique(diff_intact, return_counts=True)
diff_broken_unique = np.unique(diff_broken, return_counts=True)

print(diff_intact_unique)
print(diff_broken_unique)
max(diff_broken_unique[1])

<p>The goal here is to get the index of max of [17,  1] and the get with the index 3 of [3, 6].</p>

In [ ]:
index_max_count_2 = np.where(diff_broken_unique[1]==max(diff_broken_unique[1]))
print(index_max_count_2)

In [ ]:
index_max_count_number_2 = diff_broken_unique[0][index_max_count_2]
index_max_count_int_2 = index_max_count_number_2.item()

print(index_max_count_number_2)
print(index_max_count_int_2)

print(type(index_max_count_number_2))
print(type(index_max_count_int_2))

<p>Index, where diff broken is greater 3.</p>

In [ ]:
deviation_2 = np.where(diff_broken > index_max_count_int_2)
deviation_2_int = deviation_2[0].item()

print(deviation_2)
print(deviation_2_int)

In [ ]:
print(array_times_3_broken)
value_before_missing_number = array_times_3_broken[deviation_2].item()
print(value_before_missing_number)

#### Answer: the missing number is:

In [ ]:
missing_value_2 = value_before_missing_number + index_max_count_int_2 
print(missing_value_2)

#### Adding the missing number to the sequence

In [ ]:
array_times_3_repaired = np.insert(array_times_3_broken, deviation_2_int + 1, missing_value_2)

print(array_times_3_repaired)
print(len(array_times_3_repaired))
print(type(array_times_3_repaired))

In [ ]:
print(array_times_3)
print(len(array_times_3))

<p>Is this generalizable into a class?<br>
Should be.</p>

<p>Missing number function</p>

In [ ]:
@timemeasure
@profile
def missing_number_1(array):
    diff = np.diff(array)
    print(diff)
    diff_unique = np.unique(diff, return_counts=True)
    print(diff_unique)
    
    index_max_count = np.where(diff_unique[1]==max(diff_unique[1]))
    # print(index_max_count)
    
    index_max_count_number = diff_unique[0][index_max_count]
    index_max_count_int = index_max_count_number.item()

    # print(index_max_count_number)
    # print(index_max_count_int)
    
    deviation = np.where(diff > index_max_count_int)
    deviation_int = deviation[0].item()
    
    value_before_missing_number = array[deviation].item()
    missing_value = value_before_missing_number + index_max_count_int 
    # print(missing_value)
    
    array_repaired = np.insert(array, deviation_int + 1, missing_value)
    return missing_value, array_repaired
    

In [ ]:
missing_value_34, array_repaired_34 = missing_number_1(array_45)

print(missing_value_34)
print(array_repaired_34)

## Median problem
#### Data

In [ ]:
a_10 = np.random.randint(1, 10, 10)
a_5 = np.array([3,1,2,4,3])

In [ ]:
print(a_10)
print(a_5)

### Solution
<p>considering the concept of the median.</p>

In [ ]:
med_10 = np.median(a_10)
med_5 = np.median(a_5)

In [ ]:
print(med_10)
print(med_5)

In [ ]:
a_10_sorted = sorted(a_10)
a_5_sorted = sorted(a_5)

In [ ]:
print(a_10_sorted )
print(a_5_sorted)

In [ ]:
a_10_sorted_index = [i for i in range(len(a_10_sorted))]
a_5_sorted_index = [i for i in range(len(a_5_sorted))]

In [ ]:
print(a_10_sorted_index)
print(a_5_sorted_index)

In [ ]:
a10_index_2 =len(a_10_sorted) // 2
a10_med_2 = a_10_sorted[a10_index_2]

In [ ]:
a5_index_2 =len(a_5_sorted) // 2
a5_med_2 = a_5_sorted[a5_index_2]

In [ ]:
print(a10_med_2)
print(a5_med_2)

## Equilibrium problem
<p>
returning the absolute difference between the right and the left half of an array,<br>
where the absolute difference is at a minimum.<br>
The array could be of size 2 to 100.000.<br>
The elements of the array are between -1000 and 1000.
</p>

#### Data

In [ ]:
print(-5)
print(abs(-5))

In [ ]:
equi_5 = np.array([3,1,2,4,3])
equi_100 = np.random.randint(-1000, 1000, 100)
equi_10  = np.random.randint(1, 10, 10)
equi_40 = np.random.randint(-20, 20, 40)

In [ ]:
print(equi_5)
print(equi_100[:10])
print(equi_10)
print(equi_40[:10])

In [ ]:
print(equi_5.shape)
print(equi_100.shape)
print(equi_10.shape)
print(equi_40.shape)

<p>Creating the index.</p>

In [ ]:
equi_5_index = [i for i in range(len(equi_5))]

print(equi_5)
print(equi_5_index)

<p>First split at index 0.</p>

In [ ]:
left_0 = equi_5[0]
sum_left_0 = np.sum(left_0)

print(left_0)
print(sum_left_0)

In [ ]:
right_0 = equi_5[1:]
sum_right_0 = np.sum(right_0)

print(right_0)
print(sum_right_0)

In [ ]:
equi_diff_0 = abs(sum_left_0 - sum_right_0)
print(equi_diff_0)

<p>Second split at index 1.</p>

In [ ]:
left_1 = equi_5[:1]
sum_left_1 = np.sum(left_1)

print(left_1)
print(sum_left_1)

In [ ]:
right_1 = equi_5[2:]
sum_right_1 = np.sum(right_1)

print(right_1)
print(sum_right_1)

In [ ]:
equi_diff_1 = abs(sum_left_1 - sum_right_1)
print(equi_diff_1)

In [ ]:
print(equi_5)
print(equi_5_index)

In [ ]:
step = 0

left_dict = dict()
right_dict = dict()
diff_dict = dict()

for i in range(len(equi_5_index)):
    # print(i)
    left_12 = equi_5[:step + 1]
    # print(left_12)
    sum_left_12 = np.sum(left_12)
    # print(sum_left_12)
    left_dict[i] = sum_left_12
    
    right_12 = equi_5[step + 1:]
    sum_right_12  = np.sum(right_12)
    right_dict[i] = sum_right_12 
    
    diff_dict[i] = abs(sum_left_12 - sum_right_12)
    
    step += 1


In [ ]:
print(step)
print(left_dict)
print(right_dict)
print(diff_dict)

In [ ]:
min_key = min(diff_dict, key = diff_dict.get)
diff_dict[min_key]

<p>Pandas overview df</p>

In [ ]:
df_diff = pd.DataFrame(pd.Series(diff_dict), columns=['diff'])
df_diff.reset_index(inplace=True, drop=False)
df_diff

In [ ]:
df_diff[df_diff['diff']==df_diff['diff'].min()]

### Creating the equlibrium function

In [ ]:
@timemeasure
@profile
def equi(s):
    
        s_index = [i for i in range(len(s))]
        
        step = 0

        diff_dict_444 = dict()

        for i in range(len(s_index)):
            left_12 = s[:step + 1]
            sum_left_12 = np.sum(left_12)

            right_12 = s[step + 1:]
            sum_right_12  = np.sum(right_12)

            diff_dict_444[i] = abs(sum_left_12 - sum_right_12)

            step += 1
            
        min_key_444 = min(diff_dict_444, key = diff_dict_444.get)
        min_diff_444 = diff_dict_444[min_key_444]
        value_44 = s[min_key_444]
            
        return diff_dict_444, min_key_444, min_diff_444, value_44


### Applying the equlibrium function

In [ ]:
diff_dict_5, min_key_5, min_diff_5, value_5 = equi(equi_5)

print(diff_dict_5)
print(f'Key: {min_key_5} / Diff: {min_diff_5} / Value: {value_5}')
print(equi_5)

In [ ]:
diff_dict_10, min_key_10, min_diff_10, value_10 = equi(equi_10)

print(diff_dict_10)
print(min_diff_10)
print(f'Key: {min_key_10} / Diff: {min_diff_10} / Value: {value_10}')
print(equi_10)

In [ ]:
equi_100
diff_dict_100, min_key_100, min_diff_100, value_100 = equi(equi_100)

print(diff_dict_100)
print(f'Key: {min_key_100} / Diff: {min_diff_100 }')

In [ ]:
diff_dict_40, min_key_40, min_diff_40, value_40 = equi(equi_40)

print(diff_dict_40)
print(f'Key: {min_key_40} / Diff: {min_diff_40} / Value: {value_40}')
print(equi_40)

#### Alternative version of the equilibrium function

In [ ]:
@timemeasure
@profile
def equi_calc_2(array_777):
    
    sum_left = array_777[0]
    sum_right = sum(array_777) - array_777[0]
    diff = abs(sum_right - sum_left)
    
    for i in range(1, len(equi_5) - 1):
        sum_left += array_777[i]
        sum_right -= array_777[i]
        
        diff_current = abs(sum_right - sum_left)
        
        if diff > diff_current:
            diff = diff_current
    
    return diff
 

In [ ]:
print(equi_5)
equi_calc_2(equi_5)

In [ ]:
print(equi_10)
equi_calc_2(equi_10)

In [ ]:
print(equi_100[:5])
equi_calc_2(equi_100)

In [ ]:
print(equi_40[:5])

In [ ]:
equi_calc_2(equi_40)

<p>The runtime of the second func increases with the array size, while the memory footprint is lower.<br>
The first one delivers more information and stores a dict. This could explain this.</p>

### Reverse order of a sequence of numbers

In [ ]:
a_444 = np.array([5,7,2,8,3])

print(a_444)
print(a_444[-1])
print(a_444[-3])
print(a_444[-4])
print(a_444[-5])
print(a_444[-0])

<p>Numpy offers a flip function allready.</p>

In [ ]:
a_444_flip = np.flip(a_444)
print(a_444_flip)
print(len(a_444))

<p>The minus sign slices the values from the rear of the seq.<br>
The problem this slicing starts with -1 instead and -0 is equal to 0.<br>
</p>

In [ ]:
@timemeasure
@profile
def reverse_1(a_t5):
    l23= []
    for i in range(0, len(a_t5)+1):
        # print(a_t5[-i])
        l23.append(a_t5[-i])
    
    #l23.insert(6, a_t5[0]) 
    l23.pop(0)
    
    return l23
 

In [ ]:
print(a_444)
print(reverse_1(a_444))

In [ ]:
array_123 =np.array([1,2,3])
print(array_123)
print(reverse_1(array_123))

In [ ]:
array_999 = np.random.randint(20,30, 10)
print(array_999)
print(reverse_1(array_999))

In [ ]:
def cycle_2(l, k):
    result = [None] *  len(l)
    for i in range(len(l)):
        result[(i+k) % len(l)] = l[i]
    return result


In [ ]:
print(a_444)
print(len(a_444))
print(type(a_444))

In [ ]:
print(cycle_2(list(a_444), 2))

In [ ]:
print(a_444)
print(cycle_2(a_444, 1))

In [ ]:
print(a_444)
print(cycle_2(a_444, 4))

In [ ]:
print(a_444)
print(cycle_2(a_444, 5))

In [ ]:
print(a_444)
print(cycle_2(a_444, 6))

In [ ]:
print(a_444)
print(cycle_2(a_444, 9))

## String manipulaton
<p>
with the str-constructor.
</p>

In [ ]:
print(str('hello'))
print(type(str('hello')))

In [ ]:
print(str(25.6768))
print(type(str(25.6768)))
print(type(25.6768))

In [ ]:
print(str(25))
print(type(str(25)))
print(type(25))

In [ ]:
class MakingString:
    
    
    def __init__(self, str_object):
        self.object = str_object
        
    def makestr(self):
        # Updating the string object
        # This way the string methods are applied to the newly created object,
        # and not the input string.
        self.object=str(self.object)
        return str(self.object)

    def strtype(self):
        return(type(self.object))
    
    def printstr(self):
        return(print(self.object))
    
    def concat_str(self):
        text=""
        for arg in list(self.object):
            text += " " +  str(arg) + " "
        return text


In [ ]:
make_str_1 = MakingString(17689)
print(make_str_1)
print(type(make_str_1))
print(type(str(make_str_1)))

#### Creating a class instance and applying methods

In [ ]:
make_str_1.makestr()

In [ ]:
make_str_1.strtype()

In [ ]:
make_str_1.printstr()

<p>
First use type-method, then makestr.
</p>

In [ ]:
make_str_2 = MakingString(2000)
print(make_str_2.strtype())

In [ ]:
print(make_str_2.makestr())
print(type(make_str_2.makestr()))

In [ ]:
print(make_str_2.strtype())

#### Does concat work?

In [ ]:
make_str_3 = MakingString([17689, 2423423])

In [ ]:
make_str_3.printstr()

In [ ]:
make_str_3.concat_str()

#### Slicing strings

In [ ]:
tv_string = "The sun always shines on tv."
print(tv_string)
print(type(tv_string))

In [ ]:
print(tv_string[:3])
print(tv_string[5])
print(tv_string[-1])
print(tv_string[3:])

In [ ]:
print(tv_string.index('i'))

In [ ]:
tv_dict = dict()

for i in tv_string:
    key_string = tv_string.index(i)
    tv_dict[key_string] = i

tv_dict 

In [ ]:
tv_sun = tv_string.replace('tv', 'the sun')
print(tv_sun)

In [ ]:
tv_sun_upper = tv_sun.upper()
tv_sun_upper 

In [ ]:
tv_sun_lower = tv_sun_upper.lower()
tv_sun_lower

In [ ]:
tunnel_list = \
["And", "the", "big", "wheel", "keep", "on", "turning", "neon burning", "up", 
"above"]

print(tunnel_list)

In [ ]:
tunnel_text =  ' '.join(tunnel_list)
print(tunnel_text)

In [ ]:
tunnel_text_2 =  '_'.join(tunnel_list)
print(tunnel_text_2)

#### Splitting a string into a list.

In [ ]:
ghost_train = "And I've been riding on a ghost train where the cars they scream and slam"
print(ghost_train)

In [ ]:
ghost_train_list = ghost_train.split(" ")
print(ghost_train_list)

In [ ]:
tunnel_text_3 = tunnel_text_2.split("_")
print(tunnel_text_3)

#### Applying str methods to data frames

In [ ]:
models_23= \
pd.DataFrame(zip(['ford', 'mazda', 'chrysler'], 
                 ['sonic', 'silver', 'tanker'],
                 [10,11,12],
                 ['Famiely', 'Sport', 'Famiely']),
                 columns=['brand', 'model', 'usage', 'Lifestyle'])

models_23

In [ ]:
models_23.info()

In [ ]:
models_23['brand'] = models_23['brand'].str.capitalize()
models_23

In [ ]:
models_23.columns = models_23.columns.str.capitalize()

In [ ]:
models_23

In [ ]:
models_23['Model'] = models_23['Model'].str.upper()

<p>Replacing misspelling.</p>

In [ ]:
models_23['Lifestyle'] = models_23['Lifestyle'].str.replace('Famiely', 'Family')
models_23

#### String encrpytion

<p>
by simply shifting the character n-times (Caesar encryption).
</p>

In [ ]:
def encryption(text, key):
    
    alphabet='a bcdefghijklmnopqrstuvwxyz.,:!?'
    
    encrypted_text = ''

    # Shifting the chars
    for char in text.lower():
        idx = (alphabet.index(char) + key) % len(alphabet)
        encrypted_text = encrypted_text + alphabet[idx]

    return encrypted_text

In [ ]:
print(encryption('Aquitani', 1))

In [ ]:
print(encryption('Belga are the bravest', 6))

In [ ]:
caesar_from_gaul = \
"All Gaul is divided into three parts, one of which the Belgae inhabit, the Aquitani another, those who in their own language are called Celts, in our Gauls, the third."
print(caesar_from_gaul)

In [ ]:
encrypto_caesar = encryption(caesar_from_gaul, 10)
print(encrypto_caesar)

In [ ]:
def decryption(text, key):
    
    alphabet='a bcdefghijklmnopqrstuvwxyz.,:!?'
    
    encrypted_text = ''

    # Shifting the chars
    for char in text.lower():
        idx = alphabet.index(char) - key
        encrypted_text = encrypted_text + alphabet[idx]

    return encrypted_text

In [ ]:
print(decryption('j.?s!jxs', 10))

In [ ]:
print(decryption(encrypto_caesar, 10))

### Upper or lower
<p>
depending on conditions.
</p> 
<p>
Depending on startswith t.
</p>

In [ ]:
text_444 = \
" One part of these, which it has been said that the Gauls occupy, \
takes its beginning at the river Rhone ; it is bounded by the river Garonne, \
the ocean, and the territories of the Belgae; it borders, too, on the side of the \
Sequani and the Helvetii, upon the river Rhine , and stretches toward the north."

print(text_444[:40])

In [ ]:
text_444_split = text_444.split()
print(text_444_split[:5])

In [ ]:
for i in range(len(text_444_split)):
    # print(text_444_split[i])
    
    if text_444_split[i].startswith('t'):
        text_444_split[i] =  text_444_split[i].upper()
    else:
        text_444_split[i] =  text_444_split[i].lower()
        
print(text_444_split[:20])

In [ ]:
text_444_join = " ".join(text_444_split)
text_444_join

<p>
Depending even or whole index number.
</p>

In [ ]:
text_343 = \
" Aquitania extends from the river Garonne to the Pyrenaean \
mountains and to that part of the ocean which is near Spain"

In [ ]:
word_list = text_343.split()

for i in range(len(word_list)):
    if i%2 == 0:
        word_list[i] = word_list[i].lower()
    else:
        word_list[i] = word_list[i].upper()

In [ ]:
word_text = " ".join(word_list)
word_text

In [ ]:
word_list_2 = text_343.split()

for i in range(len(word_list_2)):
    if i%2 == 0:
        word_list_2[i] = word_list_2[i].replace(word_list_2[i], "§§§")
    else:
        word_list_2[i] = word_list_2[i].replace(word_list_2[i], "@@@")
        
word_list_2[:10]

### Regex with re

In [ ]:
# import re
text_6777 = \
"Induced by these considerations, and influenced by the authority of Orgetorix, \
they determined to provide such things as were necessary for their expedition-to \
buy up as great a number as possible of beasts of burden and wagons-to make their \
sowings as large as possible, so that on their march plenty of corn might be in \
store-and to establish peace and friendship with the neighboring states."

In [ ]:
find_and = re.findall('and', text_6777)
print(find_and)
print(len(find_and))

In [ ]:
search_bth = re.search(r"\bth",text_6777)

print(search_bth.string[:10])
print(search_bth.span())
print(search_bth.group())


In [ ]:
text_6777_split = re.split(" ", text_6777)
print(text_6777_split[:20])

In [ ]:
text_6777_a = re.sub("by", "@@@@", text_6777)
text_6777_a[:60]

#### Extracting temperatures

In [ ]:
text_999=\
"Let's consider the following temperatures using the Celsius scale: +23 C, 0 C, -20.0 C, \
-2.2 C, -5.65 C, 0.0001 C. To convert them to the Fahrenheit scale you have \
to multiply the number by 9/5 and add 32 to the result. Therefore, the \
corresponding temperatures in the Fahrenheit scale will be: \
+73.4 F, 32 F, -4.0 F, +28.04 F, 21.83 F, +32.00018 F."

In [ ]:
text_999

In [ ]:
# Define a pattern to search for valid temperatures in text
pattern = re.compile(r"[+-]?\d+.?[\d]*? [CF]")
pattern_2 = re.compile(r'[+-]?\d+\.?\d* [CF]')
# [\s\s][C F]
# [+-]?[ \d]?[\s\S]?
# Print the temperatures out
print(re.findall(pattern, text_999))
print(re.findall(pattern_2, text_999))

In [ ]:
matches_storage = re.finditer(pattern, text_999)

# Loop over matches_storage and print out item properties
for match in matches_storage:
    print('Matching sequence = ' + match.group())
    print('Start index = ' + str(match.start()))
    print('End index = ' + str(match.end()))

#### Extracting email-adresses

In [ ]:
text_emails = \
"This battle ended, that he fabius.metellus@gmail.com might be able to come up with the remaining forces \
of the Helvetii, he procures a bridge to be made across the Saone , and thus leads \
his army over. The Helvetii like julius.caesar@outlook.com confused by his sudden arrival, when they found that he \
had effected in one day, what they, themselves had with the utmost difficulty \
accomplished in twenty namely, hannibal.barka@wechat.ch, the crossing of the river, send embassadors to him; \
at the head of which embassy was Divico, who had been commander peril.scott@gmx.de of the Helvetii, \
in the war against Cassius cassius.scipio@online.network."

In [ ]:
email_pattern = re.compile(r"[\w.]*@\w*.\w*")
# [\w\.]+ @ [a-z]+\.[a-z]+
print(re.findall(email_pattern, text_emails ))

In [ ]:
matches_emails = re.finditer(email_pattern, text_emails)

for match in matches_emails:
    print('Matching sequence = ' + match.group())
    print('Start index = ' + str(match.start()))
    print('End index = ' + str(match.end()))

#### Password check
<p>
for password condtions.
</p>

In [ ]:
password_1 = "80wwdfgdfEre%_-"
re.findall(r"^[a-zA-Z0-9_\-\$\%\ß\?]{3,16}$", password_1)

In [ ]:
def password_check(password):
    if re.findall(r"^[a-zA-Z0-9_\-\$\%\?]{3,16}$", password):
        print('Password allowed.')
    else:
        print("Bad password.")
        
password_check(password_1)

In [ ]:
# § not included in pattern
password_2 = "80wwdfgdfEre%_-§§§"
password_check(password_2)

#### Extract only the strings 
<p>from the battles list without the year numbers.</p>

In [ ]:
battles = ["Battle of Bannockburn, 1314, Scots, English, Scots",
           "Battle of Freiburg, 1644, French, Imperium, indecisive"]

In [ ]:
pattern = re.compile(r', \d+,')
print(pattern)

In [ ]:
battles[0]

In [ ]:
split_result = re.split(pattern, battles[0])
print(split_result)

In [ ]:
movie_and_director = ', '.join(split_result )
print(movie_and_director)

#### Function

In [ ]:
battle_strings=[]

for battle in battles:
    split_result = re.split(pattern, battle)
    battle_string = ",".join(split_result)
    battle_strings.append(battle_string)
    
print(battle_strings)

### The Pandas apply function

In [ ]:
# print(os.getcwd())
student = pd.read_csv("csv/student/student-mat.csv", sep=";")

In [ ]:
student.columns

In [ ]:
student.head(2)

In [ ]:
student.info()

In [ ]:
math_scores = ['G1', 'G2', 'G3']
student[math_scores].head()

In [ ]:
student[math_scores].describe()

#### Finding the most frequent unique value
<p>in columns of a df.</p>

In [ ]:
student.mode()

#### Self defined mode function

In [ ]:
def mode_function(series):
    col = list(series)
    items_output = []
    # print(col)
    # Set allows only unique values
    items = [(x, col.count(x)) for x in set(series)]
    # reduce() operates pairwise
    output = reduce(lambda x, y: x if x[1] > y[1] else y, items)
    # Return the item with the highest counts
    return output[0]


#### Applying the mode func on the student data frame

In [ ]:
student_mode = student.apply(mode_function)
print(student_mode)

In [ ]:
def mathscores_classification(input_col):
    average = np.mean(input_col)
    if average < 5:
        return [average, 'low_score']
    if average >= 5 and average < 15:
        return [average, 'moderate score']
    if average >= 15:
        return [average, 'high score']


#### Arguments of result_type

In [ ]:
# col sums
mathscores_per_cohort_reduce = \
student[math_scores].apply(mathscores_classification, result_type='reduce')
mathscores_per_cohort_reduce  

In [ ]:
# col sums
mathscores_per_cohort_expand = \
student[math_scores].apply(mathscores_classification, result_type='expand')
mathscores_per_cohort_expand

<p>The average is moderate. This makes sense.</p>

In [ ]:
# row sums
student[['Mean_score_per_student', 'Score classification']] = \
student[math_scores].apply(mathscores_classification, axis=1, result_type='expand')

students_classified = \
student[['G1', 'G2', 'G3','Mean_score_per_student', 'Score classification']]

In [ ]:
students_classified.head()

In [ ]:
students_classified['Score classification'].value_counts()

<p>Most scores are moderate. This makes sense.</p>

#### Using the args argument
<p>, which allows to input multiple args arguments, if necessary.</p>

#### Normalizing the score cols
<p>In this case args arguments are not necessary.</p>

In [ ]:
def normalizing_variables(series):
   # Define the expression to rescale input series
   return series * ((max(series)-min(series))/100) + min(series)

In [ ]:
student_normalized = student[math_scores].apply(normalizing_variables)
student_normalized.head()

#### Rescaling variables with input arguments

In [ ]:
def rescaling_variables(series, low, high):
   # Define the expression to rescale input series
   return series * ((high-low)/100) + low

In [ ]:
student_rescaled = student[math_scores].apply(rescaling_variables, args=[1,10])
student_rescaled.head()

In [ ]:
def normalizing_variables(series):
   # Define the expression to rescale input series
   return series * ((max(series)-min(series))/100) + min(series)

student[math_scores].apply(normalizing_variables)

In [ ]:
student[math_scores].apply(normalizing_variables)

#### Groupby

In [ ]:
student['school'].value_counts()

In [ ]:
grouby_school=student.groupby('school')

print(grouby_school)
print(type(grouby_school))

<p>Groupby stores the grouped results as df in a tuple.<br>
In this case there are stored 2 df in the tuple.</p>

In [ ]:
print(len(grouby_school))

In [ ]:
for i in grouby_school:
    df=i[1]
    print(df.iloc[:2, 0:4])

<p>This is an iterable.</p>

In [ ]:
grouby_school['school'].count()

In [ ]:
student.groupby('school')[math_scores].mean()

In [ ]:
student.groupby('school')[math_scores].aggregate([sum, np.mean]).transpose()

#### Transform on groupby similiar to apply 

In [ ]:
student_transformed = \
student.groupby('school')[math_scores].transform(lambda x: round(x+100.345435,2))

student_transformed.head()

#### Filter with groupby

In [ ]:
groupb_ft = student.groupby(['school', 'sex'])['freetime'].mean()
groupb_ft

In [ ]:
groupby_school_sex = student.groupby(['school', 'sex'])
print(len(groupby_school_sex))

In [ ]:
groupby_school_sex['freetime'].count()


In [ ]:
freetime_filter = \
groupby_school_sex.filter(lambda x: x['freetime'].count() > 2)

freetime_filter[['school', 'sex', 'freetime']].value_counts()

#### The overweight heroes

In [ ]:
heroes_2 = pd.read_csv('csv/heroes_information.csv')

#### Adding a BMI col

In [ ]:
heroes_2['BMI'] = heroes_2.Weight / ((heroes_2.Height / 100) ** 2)

In [ ]:
heroes_2.info()

In [ ]:
plt.scatter(heroes_2['Weight'], heroes_2['Height'], edgecolor='black', color='orange', s=50)
plt.title('Relation of weight and height')
plt.xlabel('Weight')
plt.ylabel('Height')
plt.show()

In [ ]:
plt.hist(heroes_2['BMI'], color='red', edgecolor='black', linewidth=5)
plt.xlabel('BMI')
plt.ylabel('Frequency')
plt.title('Distribution of the BMI variable')
plt.show()

In [ ]:
sns.set_style('darkgrid')
plt.subplots(1,1,figsize=(10,5))
sns.boxplot(y='BMI', x='Alignment', data=heroes_2)
plt.show()

heroes_2.info()

#### Good or bad

In [ ]:
print(heroes_2['Alignment'].value_counts())

In [ ]:
print(heroes_2['Race'].unique()[:10])

In [ ]:
heroes_overweight = heroes_2[heroes_2['BMI'] > 30]

print(heroes_2.shape)
print(heroes_overweight.shape)
print(heroes_overweight[['name', 'Alignment', 'Gender', 'BMI']].head(4))

#### Mean BMI by race and gender

In [ ]:
heroes_aligned = heroes_2.groupby(['Alignment', 'Race'])
print(len(heroes_aligned))

In [ ]:
heroes_size = heroes_aligned.size()

print(type(heroes_size))
print(heroes_size.shape)
print(heroes_size.head())

In [ ]:
# Keep only groups with more than 20 valid bmi observations
heroes_aligned_filtered = heroes_aligned.filter(lambda x: x['BMI'].count() > 20)
heroes_aligned_regrouped = heroes_aligned_filtered.groupby(['Race', 'Gender'])
heroes_aligned_mean = heroes_aligned_regrouped ['BMI'].agg([np.mean, np.std])

heroes_aligned_mean

In [ ]:
heroes_2.isna().sum()